<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('codes')->delete();
        $data = array(
        [
            'parentcode' => NULL,
            'code' => 'GENDER',
            'name' => 'Gender',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'GENDER',
            'code' => 'Male',
            'name' => 'Laki-Laki',
            'description' => NULL,
            'value' => 'Male',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'GENDER',
            'code' => 'Female',
            'name' => 'Perempuan',
            'description' => NULL,
            'value' => 'Female',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'RELIGION',
            'name' => 'Agama',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Islam',
            'name' => 'Islam',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Katolik',
            'name' => 'Katolik',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Protestan',
            'name' => 'Protestan',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Buddha',
            'name' => 'Buddha',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Hindu',
            'name' => 'Hindu',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'RELIGION',
            'code' => 'Khonghucu',
            'name' => 'Khonghucu',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'ACADEMIC',
            'name' => 'Gelar akademik',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'SD',
            'name' => 'Sekolah Dasar',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'SMP',
            'name' => 'Sekolah Menengah Pertama',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'SMA',
            'name' => 'Sekolah Menengah Atas dan Setara',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'Diploma',
            'name' => 'Diploma',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'Sarjana',
            'name' => 'Sarjana (S1)',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'Magister',
            'name' => 'Magister (S2)',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'ACADEMIC',
            'code' => 'Doktor',
            'name' => 'Doktor (S3)',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'MARRIAGE',
            'name' => 'Status Pernikahan',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'MARRIAGE',
            'code' => 'Single',
            'name' => 'Lajang',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'MARRIAGE',
            'code' => 'Menikah',
            'name' => 'Menikah',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'PID',
            'name' => 'Personal Identification Document',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'PID',
            'code' => 'KTP',
            'name' => 'KTP',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'PID',
            'code' => 'Paspor',
            'name' => 'Paspor',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'EMPSTATUS',
            'name' => 'Status Kepegawaian',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'EMPSTATUS',
            'code' => 'EMPSTATUS01',
            'name' => 'Permanen',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'EMPSTATUS',
            'code' => 'EMPSTATUS02',
            'name' => 'Kontrak',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'TRT',
            'name' => 'Transcation Type',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'TRT',
            'code' => 'TRTCS',
            'name' => 'Cash',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'TRT',
            'code' => 'TRTCR',
            'name' => 'Credit',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        // How a storefront order is paid for. Cash and Credit above describe a
        // counter sale; these two are what checkout offers, and what
        // transactions.payment_type holds. Kept here as well as in
        // add_payment_method_codes because run() deletes the table first: a
        // row that exists only as a migration would not survive a re-seed.
        [
            'parentcode' => 'TRT',
            'code' => 'TRTMN',
            'name' => 'Transfer Manual',
            'description' => 'Transfer ke rekening bank, dengan bukti pembayaran diunggah pembeli',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'TRT',
            'code' => 'TRTQR',
            'name' => 'QRIS',
            'description' => 'Bayar dengan memindai QRIS',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'UOM',
            'name' => 'SATUAN',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => 12,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'UOM00',
            'name' => '-',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'BUA',
            'name' => 'BUAH',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'EKR',
            'name' => 'EKOR',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'HRI',
            'name' => 'HARI',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'KG',
            'name' => 'KILOGRAM',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'UOM',
            'code' => 'PCS',
            'name' => 'PCS',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'STS',
            'name' => 'Status Transaksi',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSSV',
            'name' => 'Saved',
            'description' => 'Disimpan',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSAP',
            'name' => 'Approval',
            'description' => 'Menunggu Pengesahan',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
                [
            'parentcode' => 'STS',
            'code' => 'STSOK',
            'name' => 'Completed',
            'description' => 'Selesai',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSVD',
            'name' => 'Void',
            'description' => 'Dihapus/Dibatalkan',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSRJ',
            'name' => 'Rejected',
            'description' => 'Ditolak',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSPY',
            'name' => 'Payment',
            'description' => 'Menunggu Pembayaran',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        // Between waiting for money and having seen it: the buyer has uploaded
        // proof and somebody has to look at it. Set by OrderController when a
        // PAYMENT attachment arrives -- see add_confirmation_payment_status for
        // why it is not the existing STSCF.
        [
            'parentcode' => 'STS',
            'code' => 'STSCP',
            'name' => 'Confirmation Payment',
            'description' => 'Menunggu Konfirmasi Pembayaran',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSPD',
            'name' => 'Paid',
            'description' => 'Dibayar',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSCF',
            'name' => 'Confirmed',
            'description' => 'Dikonfirmasi',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSDV',
            'name' => 'Delivery',
            'description' => 'Dalam Perjalanan',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STS',
            'code' => 'STSCM',
            'name' => 'Complained',
            'description' => 'Komplain',
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'STP',
            'name' => 'Section Type',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STP',
            'code' => 'STPFP',
            'name' => 'Section Folder',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STP',
            'code' => 'STPSC',
            'name' => 'Single Content',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STP',
            'code' => 'STPMC',
            'name' => 'Multiple Content',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STP',
            'code' => 'STPIG',
            'name' => 'Image Gallery',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STP',
            'code' => 'STPCA',
            'name' => 'Call To Action',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'BST',
            'name' => 'Business Type',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'BST',
            'code' => 'Online Store',
            'name' => 'Toko Online',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'BSTRL',
            'name' => 'Business Role',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'BSTRL',
            'code' => 'OWNER',
            'name' => 'Owner',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'BSTRL',
            'code' => 'STAFF',
            'name' => 'Staff',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'BSTRL',
            'code' => 'MANAGEMENT',
            'name' => 'Management',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'CRPR',
            'name' => 'Produk Sertifikat',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'CRPR',
            'code' => 'CRPRHALAL',
            'name' => 'Sertifikat Halal',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'CRPR',
            'code' => 'CRPRSDHLL',
            'name' => 'Self Declaration Halal',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'STSPRD',
            'name' => 'Status',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STSPRD',
            'code' => 'STSPRD-WAPROV',
            'name' => 'Menunggu Pengecekan',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STSPRD',
            'code' => 'STSPRD-RJCT',
            'name' => 'Ditolak',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'STSPRD',
            'code' => 'STSPRD-APRV',
            'name' => 'Diterima',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => NULL,
            'code' => 'VARIANTS',
            'name' => 'Variasi Produk',
            'description' => NULL,
            'value' => NULL,
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'VARIANTS',
            'code' => 'Warna',
            'name' => 'Warna',
            'description' => NULL,
            'value' => 'Colors',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'VARIANTS',
            'code' => 'Ukuran',
            'name' => 'Ukuran',
            'description' => NULL,
            'value' => 'Sizes',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'VARIANTS',
            'code' => 'Model',
            'name' => 'Model',
            'description' => NULL,
            'value' => 'Models',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'VARIANTS',
            'code' => 'Tipe',
            'name' => 'Tipe',
            'description' => NULL,
            'value' => 'Types',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
        [
            'parentcode' => 'VARIANTS',
            'code' => 'Rasa',
            'name' => 'Rasa',
            'description' => NULL,
            'value' => 'Flavours',
            'datatype' => 'STRING',
            'order' => NULL,
        ],
      );

        foreach($data as $row)
          \DB::table('codes')->insert($row);
    }
}
